### PR TITLE
Added Virtual Machine guide and Hardware Guide

### PR DESCRIPTION
**Pull request by ghost**
Added Virtual Machine guide and Hardware Guide
I have added guide to VM and Hardware and all the commands have been double checked to remove any ambiguity and it has been made sure by running them in the given environment.
Exception :- QEMU , VirtualBox for macos for m1 , m2 is not suited as VM automatically hangs/turnsoff though issue has been raised in the respective orgs if there is any update i will make sure to update them here.

### CODE REVIEW

**Comment by ghost** [comment]
The only file which is empty is app-testing(link has not been provided) and that file will only contain info/documentation regarding apps/activities which uses sensors , GPIO pins and are only related with RPi and it will be edited and completed as time progresses.

**Comment by chimosky** [comment]
>  Exception :- QEMU , VirtualBox for macos for m1 , m2 is not suited as VM automatically hangs/turnsoff though issue has been raised in the respective orgs if there is any update i will make sure to update them here.

Did you state this in the doc?

**Comment by ghost** [comment]
Screenshot 2024-02-15 at 8 50 20 PM


I have written like this what is suited best for mac users in the doc.
but havent mentioned in the doc specifically regarding QEMU for m1 , m2 users. @chimosky

**Comment by chimosky** [comment]
> Screenshot 2024-02-15 at 8 50 20 PM
> 
> I have written like this what is suited best for mac users in the doc. but havent mentioned in the doc specifically regarding QEMU for m1 , m2 users. @chimosky

That's what I was asking about, you should state clearly what works and for what devices as you know this.

**Pull request merged**
